#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['FILESYSTEM_STDIO_EXPORTS'])

def build(bld):
	source = [
		'basefilesystem.cpp',
		'basefilesystemasync.cpp',
		'filetracker.cpp',
		'filesystemasync.cpp',
		'filesystem_stdio.cpp',
		'../public/kevvaluescompiler.cpp',
		'../public/zip_utils.cpp',
		'QueuedLoader.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS != 'win32':
		source += [
			'linux_support.cpp'
		]

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib',
		'vpklib'
	]

	bld.shlib(
		target = 'filesystem_stdio',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
