#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['SOUNDEMITTERSYSTEM_EXPORTS'])

def build(bld):
	source = [
		'soundemittersystembase.cpp',
		'../public/SoundParametersInternal.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib'
	]

	bld.shlib(
		target = 'soundemittersystem',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
