#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['MATHLIB_EXTENDED_LIB', 'SOURCE1'])

def build(bld):
	source = [
		'../disjoint_set_forest.cpp',
		'../dynamictree.cpp',
		'../eigen.cpp',
		'../simdvectormatrix.cpp',
		'../femodel.cpp',
		'../femodelbuilder.cpp',
		'../feagglomerator.cpp',
		'../svd.cpp',
		'../transform.cpp',
		'../femodeldesc.cpp',
		'../softbody.cpp',
		'../softbodyenvironment.cpp'
	]

	includes = [
		'../../public/mathlib'
	]

	libs = []

	bld.stlib(
		target = 'mathlib_extended',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
