#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'base_gcmessages.pb.cc',
		'cstrike15_gcmessages.pb.cc',
		'cstrike15_usermessages.pb.cc',
		'engine_gcmessages.pb.cc',
		'gcsdk_gcmessages.pb.cc',
		'gcsystemmsgs.pb.cc',
		'netmessages.pb.cc',
		'network_connection.pb.cc',
		'steammessages.pb.cc'
	]

	includes = [
		'../thirdparty/protobuf-3.2.0/src'
	]

	libs = []

	bld.stlib(
		target = 'generated_proto',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
