#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'videocfg.cpp'
	]

	includes = [
		'../public',
		'../public/tier1',
		'../public/videocfg'
	]

	libs = []

	bld.stlib(
		target = 'videocfg',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
