#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['STUDIORENDER_EXPORTS'])

def build(bld):
	source = [
		'studiorender.cpp',
		'studiorendercontext.cpp',
		'flexrenderdata.cpp',
		'r_studio.cpp',
		'r_studiodecal.cpp',
		'r_studiodraw.cpp',
		'r_studiodraw_computeflexedvertex.cpp',
		'r_studioflex.cpp',
		'r_studiosubd.cpp',
		'r_studiosubd_patches.cpp',
		'r_studiogettriangles.cpp',
		'r_studiolight.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'tier3',
		'interfaces',
		'vstdlib',
		'bitmap',
		'mathlib'
	]

	bld.shlib(
		target = 'studiorender',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
