#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['FIXED_POINT', 'FLOAT_APPROX', 'USE_ALLOCA', 'CUSTOM_MODES'])

def build(bld):
	source = [
		'libcelt/bands.c',
		'libcelt/celt.c',
		'libcelt/cwrs.c',
		'libcelt/entcode.c',
		'libcelt/entdec.c',
		'libcelt/entenc.c',
		'libcelt/header.c',
		'libcelt/kiss_fft.c',
		'libcelt/laplace.c',
		'libcelt/mathops.c',
		'libcelt/mdct.c',
		'libcelt/modes.c',
		'libcelt/pitch.c',
		'libcelt/plc.c',
		'libcelt/quant_bands.c',
		'libcelt/rate.c',
		'libcelt/vq.c'
	]

	includes = []

	libs = []

	bld.stlib(
		target = 'celt',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
