#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'dmxattribute.cpp',
		'dmxelement.cpp',
		'dmxloader.cpp',
		'dmxloadertext.cpp',
		'dmxserializationdictionary.cpp',
		'utlsoacontainer_serialization.cpp'
	]

	includes = [
		'../public'
	]

	libs = []

	bld.stlib(
		target = 'dmxloader',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
