#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['VSCRIPT_DLL_EXPORT'])

def build(bld):
	source = [
		'vscript.cpp',
		'languages/squirrel/vsquirrel/vsquirrel.cpp',
		'languages/squirrel/squirrel/sqapi.cpp',
		'languages/squirrel/squirrel/sqbaselib.cpp',
		'languages/squirrel/squirrel/sqclass.cpp',
		'languages/squirrel/squirrel/sqcompiler.cpp',
		'languages/squirrel/squirrel/sqdebug.cpp',
		'languages/squirrel/squirrel/sqfuncstate.cpp',
		'languages/squirrel/squirrel/sqlexer.cpp',
		'languages/squirrel/squirrel/sqmem.cpp',
		'languages/squirrel/squirrel/sqobject.cpp',
		'languages/squirrel/squirrel/sqstate.cpp',
		'languages/squirrel/squirrel/sqtable.cpp',
		'languages/squirrel/squirrel/sqvm.cpp',
		'languages/squirrel/sqdbg/sqrdbg.cpp',
		'languages/squirrel/sqdbg/sqdbgserver.cpp',
		'languages/squirrel/sqstdlib/sqstdaux.cpp',
		'languages/squirrel/sqstdlib/sqstdblob.cpp',
		'languages/squirrel/sqstdlib/sqstdmath.cpp',
		'languages/squirrel/sqstdlib/sqstdrex.cpp',
		'languages/squirrel/sqstdlib/sqstdstream.cpp',
		'languages/squirrel/sqstdlib/sqstdstring.cpp',
		'languages/squirrel/sqplus/SqPlus.cpp',
		'languages/squirrel/sqplus/SquirrelBindingsUtils.cpp',
		'languages/squirrel/sqplus/SquirrelObject.cpp',
		'languages/squirrel/sqplus/SquirrelVM.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += ['languages/squirrel/sqplus/SquirrelBindingsUtilsWin32.cpp']

	includes = [
		'languages/squirrel/include',
		'languages/squirrel/sqplus',
		'../public',
		'../public/tier0',
		'../public/tier1'
	]

	libs = [
		'tier0',
		'tier1',
		'interfaces',
		'vstdlib',
		'mathlib'
	]

	bld.shlib(
		target = 'vscript',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
