#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['LAUNCHERONLY'])

def build(bld):
	source = [
		'../public/filesystem_init.cpp',
		'launcher.cpp',
		'reslistgenerator.cpp'
	]

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib',
		'togl',
		'appframework'
	]

	bld.shlib(
		target = 'launcher',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
