#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	if conf.env.DEST_OS == 'win32':
		conf.env.append_unique('DEFINES', ['fopen=dont_use_fopen'])

def build(bld):
	source = [
		'vtf.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += ['s3tc_decode.cpp']

	includes = [
		'../public',
		'../public/tier1'
	]

	libs = []

	bld.stlib(
		target = 'vtf',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
