#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'blocksort.c',
		'bzip2.c',
		'bzlib.c',
		'compress.c',
		'crctable.c',
		'decompress.c',
		'huffman.c',
		'randtable.c'
	]

	includes = []

	libs = []

	bld.stlib(
		target = 'bzip2',
		features = 'c',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
