#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['FAST_MATERIALVAR_ACCESS'])

def build(bld):
	source = [
		'BaseShader.cpp',
		'ShaderDLL.cpp',
		'shaderlib_cvar.cpp'
	]

	includes = [
		'../../public',
		'../../public/tier1',
		'..'
	]

	libs = []

	bld.stlib(
		target = 'shaderlib',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
