#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['MDLCACHE_DLL_EXPORT'])

def build(bld):
	source = [
		'datacache.cpp',
		'mdlcache.cpp',
		'mdlcombine.cpp',
		'vtfcombine.cpp',
		'resourceaccesscontrol.cpp',
		'precachesystem.cpp',
		'../public/studio.cpp',
		'../public/studio_virtualmodel.cpp',
		'../common/studiobyteswap.cpp',
		'../utils/common/datalinker.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'tier3',
		'interfaces',
		'vstdlib',
		'mathlib'
	]

	bld.shlib(
		target = 'datacache',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
