#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'bone_setup.cpp',
		'bone_ik.cpp',
		'bone_utils.cpp',
		'bone_decode.cpp',
		'bone_constraints.cpp'
	]

	includes = []

	libs = []

	bld.stlib(
		target = 'bonesetup',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
