#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'AppSystemGroup.cpp',
		'../public/filesystem_init.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'VguiMatSysApp.cpp',
			'matsysapp.cpp',
			'WinApp.cpp'
		]
	else:
		source += ['posixapp.cpp']

	if bld.env.SDL:
		source += ['sdlmgr.cpp']

	if bld.env.DEST_OS == 'darwin':
		source += ['glmrendererinfo_osx.mm'] if bld.env.SDL else ['cocoamgr.mm']

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	libs = []

	bld.stlib(
		target = 'appframework',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
