#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'BitmapFont.cpp',
		'FontAmalgam.cpp',
		'fontmanager.cpp',
		'FontEffects.cpp',
		'fonttexturecache.cpp',
		'texturedictionary.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += ['Win32Font.cpp']
	else:
		source += ['stbfont.cpp']

	includes = [
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common'
	]

	libs = []

	bld.stlib(
		target = 'vgui_surfacelib',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
