#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'vaudio_minimp3.cpp',
		'../../../public/tier0/memoverride.cpp'
	]

	includes = []

	libs = [
		'tier0',
		'tier1',
		'interfaces',
		'vstdlib'
	]

	bld.shlib(
		target = 'vaudio_minimp3',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
