#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'main.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'launcher_main.rc',
			'../launcher/res/launcher.ico'
		]

	includes = [
		'../public'
	]

	libs = []

	bld(
		target = 'csgo_launcher',
		features = 'c cxx cxxprogram',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.PREFIX,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
