#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['VSTDLIB_DLL_EXPORT'])

def build(bld):
	source = [
		'coroutine.cpp',
		'cvar.cpp',
		'jobthread.cpp',
		'keyvaluessystem.cpp',
		'random.cpp',
		'vcover.cpp',
		'eventsystem.cpp',
		'vstrtools.cpp',
		'vstdlib_strtools.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += ['processutils.cpp']
		if bld.env.ALLOW64:
			source += ['getstackptr64.masm']

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1'
	]

	libs = [
		'tier0',
		'tier1',
		'interfaces'
	]

	bld.shlib(
		target = 'vstdlib',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
