#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['BENCHMARK', 'VGUIMATSURFACE_DLL_EXPORT', 'GAMEUI_EXPORTS', 'ENABLE_CHROMEHTMLWINDOW'])

def build(bld):
	source = [
		'Clip2D.cpp',
		'Cursor.cpp',
		'../public/filesystem_helpers.cpp',
		'Input.cpp',
		'MatSystemSurface.cpp',
		'../vgui2/src/vgui_key_translation.cpp',
		'../public/vgui_controls/vgui_controls.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'memorybitmap.cpp',
			'../vgui2/src/htmlwindow.cpp'
		]

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	libs = [
		'tier0',
		'vgui_controls',
		'vgui_surfacelib',
		'bitmap',
		'dmxloader',
		'tier1',
		'tier2',
		'tier3',
		'interfaces',
		'vstdlib',
		'mathlib'
	]

	if bld.env.SDL:
		libs += ['SDL2']

	bld.shlib(
		target = 'vguimatsurface',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
