#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['JPH_DISABLE_CUSTOM_ALLOCATOR', 'JPH_DEBUG_RENDERER', 'GAME_PORTAL2'])

def build(bld):
	source = [
		'../public/collisionutils.cpp',
		'../public/filesystem_helpers.cpp',
		'vjolt_collide.cpp',
		'vjolt_collide_trace.cpp',
		'vjolt_constraints.cpp',
		'vjolt_controller_fluid.cpp',
		'vjolt_controller_motion.cpp',
		'vjolt_controller_player.cpp',
		'vjolt_controller_vehicle.cpp',
		'vjolt_controller_shadow.cpp',
		'vjolt_debugrender.cpp',
		'vjolt_environment.cpp',
		'vjolt_friction.cpp',
		'vjolt_interface.cpp',
		'vjolt_keyvalues_schema.cpp',
		'vjolt_object.cpp',
		'vjolt_objectpairhash.cpp',
		'vjolt_parse.cpp',
		'vjolt_querymodel.cpp',
		'vjolt_surfaceprops.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../thirdparty/JoltPhysics'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib',
		'mathlib',
		'JoltPhysics'
	]

	bld.shlib(
		target = 'vphysics',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
