#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'../../../tier1/interface.cpp',
		'../frame_encoder/voice_codec_frame.cpp',
		'voiceencoder_celt.cpp',
		'../../../public/tier0/memoverride.cpp'
	]

	includes = [
		'source/libcelt',
		'../frame_encoder',
		'../..',
		'../../audio/public'
	]

	libs = [
		'tier0',
		'tier1',
		'interfaces',
		'vstdlib',
		'celt'
	]

	bld.shlib(
		target = 'vaudio_celt',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
