#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES', ['NO_STRING_T'])

def build(bld):
	source = [
		'inputstacksystem.cpp',
		'inputsystem.cpp',
		'steamcontroller.cpp',
		'key_translation.cpp',
		'../common/platforminputdevice.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'joystick.cpp',
			'xcontroller.cpp'
		]
	elif bld.env.DEST_OS == 'darwin':
		source += ['joystick_osx.cpp']
	elif bld.env.DEST_OS == 'linux':
		source += ['joystick_linux.cpp']

	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib',
		'mathlib',
		'steam_api'
	]

	if bld.env.SDL:
		libs += ['SDL2']

	bld.shlib(
		target = 'inputsystem',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
