#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'bitmap.cpp',
		'colorconversion.cpp',
		'floatbitmap.cpp',
		'floatbitmap2.cpp',
		'floatbitmap3.cpp',
		'floatbitmap_bilateralfilter.cpp',
		'floatcubemap.cpp',
		'imageformat.cpp',
		'psd.cpp',
		'psheet.cpp',
		'resample.cpp',
		'tgaloader.cpp',
		'texturepacker.cpp',
		'tgawriter.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'floatbitmap4.cpp'
		]

	includes = [	
		'../public',
		'../public/tier0',
		'../public/tier1'
	]

	libs = []

	bld.stlib(
		target = 'bitmap',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
