#!/usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'device_null.cpp',
		'mix.cpp',
		'simple_filter.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'device_dsound.cpp',
			'device_xaudio2.cpp',
			'windows_audio.cpp'
		]
	else:
		source += ['device_sdl.cpp']

	includes = [
		'../../public',
		'../../public/tier0',
		'../../public/tier1'
	]

	libs = []

	bld.stlib(
		target = 'soundsystem_lowlevel',
		features = 'c cxx',
		source = source,
		includes = includes,
		use = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
